### PR TITLE
Make this repository usable as an OpenWrt feed on OpenWrt SDK & add v2ray initscript

### PR DESCRIPTION
**Pull request by arinc9**
Make this repository usable as an OpenWrt feed on OpenWrt SDK.
- This is better because this is the default way of adding packages from feeds on OpenWrt SDK and there is a script to update the feeds. I have also updated the readme to reflect these changes.

Add v2ray initscript.
- There's already an initscript for v2ray on luci-app-v2ray, however, this script is much simple which just runs v2ray with the config file at `/etc/v2ray/config.json`. If the user installs luci-app-v2ray on top of v2ray-core, the initscript will be replaced with luci-app-v2ray's so it won't cause any issues.
- I don't need luci-app-v2ray but I want to start v2ray on startup. This PR achieves this.

You might have to update github-actions bot to find the new v2ray-core directory.

### CODE REVIEW

**Comment by arinc9** [comment]
@kuoruan what do you think?

**Comment by kuoruan** [comment]
Hi @arinc9, this package is only contains v2ray bin and will not contain any init.d script. (you can find my init.d scripts in luci-app-v2ray)
But you can make a pull request to openwrt/packages.

https://github.com/openwrt/packages/pull/16469

**Comment by arinc9** [comment]
> 
> 
> Hi @arinc9, this package is only contains v2ray bin and will not contain any init.d script. (you can find my init.d scripts in luci-app-v2ray)
> But you can make a pull request to openwrt/packages.
> 
> [openwrt/packages#16469](https://github.com/openwrt/packages/pull/16469)

@kuoruan I think you missed my points on the PR description. There are two changes this PR brings. I explained how the initscript I wrote will be useful. I'm also awaiting your comment for the other change.

**Comment by kuoruan** [comment]
The purpose of this repository is only provide binary file of v2ray-core.
We'd better not move the files to subdirectory, because it is easy to access when in top dir.

For the init script, I think we can put it in the README.md.

**Comment by arinc9** [comment]
We have different views of the repository, so I'm closing my PR.

**Pull request closed without merging**
